services:
  go-api:
    container_name: go-api
    build: 
      context: ./go-api
      dockerfile: Dockerfile
    ports:
      - "8888:8080"
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      DB_HOST: db
      DB_PORT: 5432
    restart: always
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres