services:
  go-api:
    container_name: go-api
    build: 
      context: ./go-api
      dockerfile: Dockerfile
    ports:
      - "8888:8080"
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      DB_HOST: db
      DB_PORT: 5432
    restart: always
    depends_on:
      - db

  nuxt-app:
    container_name: nuxt-app
    build: 
      context: ./nuxt-app
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      API_URL: http://go-api:8080
    restart: always
    depends_on:
      - go-api
  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  cache:
    container_name: cache
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    environment:
      - REDIS_PASSWORD=redis