apiVersion: v1
kind: Service
metadata:
  name: nuxt-app-service
spec:
  type: NodePort # Exposes the app externally
  selector:
    app: nuxt-app
  ports:
  - port: 80 # Internal port
    targetPort: 3000 # Port the container is listening on
    nodePort: 30000 # Optional: External access port